# Set up Nginx
FROM nginx:latest as production-stage
COPY --from=cozy-threads-client /cozy-threads/dist/ /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]