name: Build and Publish Vue Client Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_REPO: architg07/archit-stripe-client

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: architg07
        password: dckr_pat_FaI-kAJq3KFZY7qLzJYTa8XJcrw

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./client 
        file: ./client/Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}

    - name: Tag as latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker pull ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
        docker tag ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }} ${{ env.DOCKER_HUB_REPO }}:latest
        docker push ${{ env.DOCKER_HUB_REPO }}:latest
